server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
    service-url:
      defaultZone: http://dev:dev@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
  instance:
    hostname: localhost

spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://dev:dev@localhost:8888/
  # Spring security config
  security:
    user:
      name: ${CONFIG_USERNAME:dev}
      password: ${CONFIG_PASSWORD:dev}
  
  profiles:
    default: development
    active: development

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
